// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class OSInterFaceLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  OSInterFaceLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  OSInterFaceLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int sysIdleTime() {
    return _sysIdleTime();
  }

  late final _sysIdleTimePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('sysIdleTime');
  late final _sysIdleTime = _sysIdleTimePtr.asFunction<int Function()>();
}
